### ISSUE TITLE
IonicToast not show in directive

### ISSUE THREAD

**Issue by sylfree9999** [rajeshwarpatlolla/ionic-toast#11]
Hi,
Thanks for this great plugin.
But I found out it will not work in directive. Here is a [plunker.](http://plnkr.co/edit/9JJqehBT7U9uONMe8Fdy?p=preview)

Many Thanks

**Comment by rajeshwarpatlolla** [comment]
You can just use this in a function call. All you need to do is just call the ionicToast.show.
