### ISSUE TITLE
bower install error 

### ISSUE THREAD

**Issue by Jager001** [rajeshwarpatlolla/ionic-toast#13]
i have an error when i first install the toast plugin, and i dont know the reason:

E:\Workspaces\workspace-app_ionic>bower install ionic-toast --save
bower not-cached    git://github.com/driftyco/ionic-bower.git#1.2.4
bower resolve       git://github.com/driftyco/ionic-bower.git#1.2.4
bower not-cached    git://github.com/rajeshwarpatlolla/ionic-toast.git#*
bower resolve       git://github.com/rajeshwarpatlolla/ionic-toast.git#*
bower download      https://github.com/driftyco/ionic-bower/archive/v1.2.4.tar.g
z
bower ENORESTARGET  Tag/branch master does not exist

Additional error details:
No tags found in git://github.com/rajeshwarpatlolla/ionic-toast.git
No branches found in git://github.com/rajeshwarpatlolla/ionic-toast.git

**Comment by rajeshwarpatlolla** [comment]
I am able to install this plugin, without the errors you mentioned. Please take a look at the screenshot attached.

![screen shot 2016-05-01 at 1 12 13 pm](https://cloud.githubusercontent.com/assets/9896335/14949423/8529919c-1067-11e6-8485-0aebd185bc20.png)
