### ISSUE TITLE
Toast not displaying properly

### ISSUE THREAD

**Issue by ghost** [rajeshwarpatlolla/ionic-toast#18]
Hi,

Thanks for making this plugin - there has been a real need for one like this.  But to the problem - when I try to show the toast nothing happens.  I did some troubleshooting and found that the `<div class="ionic_tast` has display:none, and this never goes away.  The toast fires inside of it, but you never see it because the parent div always has display:none.  additionally it has padding, so it is just a black bar that sits at the top of the screen.  Any idea why this might be happening?

Update - after more research, I found more funny issues:  The inner `<div class="toast_section ionic_toast_bottom"` has bottom:10px in the css, but no position:fixed or absolute attached to it.

Update - I think I see what the issue is - toast is applying the styles and classes to the wrong element.  It is applying them to the inner div instead of the outer one.

**Comment by rajeshwarpatlolla** [comment]
Please install the latest version. I have fixed this issue.
