### ISSUE TITLE
Issue with latest updates

### ISSUE THREAD

**Issue by shajeermhmmd** [rajeshwarpatlolla/ionic-toast#20]
Thank uuu.. for this great plugin.
ionic -toast previous version working well, but some problem with latest updation, recently i installed ionic-toast with bower then i got a conflict for file version after that i choose latest version but the toast did't worked. So i replaced the newly installed file in the lib folder with older version then it worked .

**Comment by rajeshwarpatlolla** [comment]
Please install from master `bower install ionic-toast#master`. In the next one or two days you can expect a proper release. In the meantime please use the code from master, which is working fine.

**Comment by rajeshwarpatlolla** [comment]
Please use the [latest version](https://github.com/rajeshwarpatlolla/ionic-toast/releases/tag/v0.4.1)
