### ISSUE TITLE
v3.0 not working

### ISSUE THREAD

**Issue by toumiGit** [rajeshwarpatlolla/ionic-toast#21]
I just installed the version 3.0 and it did not work. ( no output in the console nothing at all)

i downgraded to v2.0 and it worked fine. please let me know if you want more details.

**Comment by mattdelaf** [comment]
Same for me thanks @toumiGit  !

**Comment by rajeshwarpatlolla** [comment]
Please install from master `bower install ionic-toast#master`. In the next one or two days you can expect a proper release. In the meantime please use the code from master, which is working fine.

**Comment by rajeshwarpatlolla** [comment]
Please install using `bower install ionic-toast#master`

**Comment by TabraizAhmad** [comment]
Hi rajesh, the master is also not working properly, there is no backgroung color

**Comment by rajeshwarpatlolla** [comment]
This issue has been fixed. Please pull the latest code from the [new release](https://github.com/rajeshwarpatlolla/ionic-toast/releases/tag/v0.4.1)

**Comment by RameshkrishnanV** [comment]
hi rajesh.. the toast is not displaying...
