### ISSUE TITLE
'translate' support in ionic toast

### ISSUE THREAD

**Issue by chiragandroid** [rajeshwarpatlolla/ionic-toast#24]
Ionic toast is the best tool in ionic to display all types of messages.
i am working on application that has multiple countries,currencies supported.

Now i want to display translated Messages, i am using angular-translate for all messages,forms and text in HTML. now coming to JS file. i want to translate messages that are in ionic-toast.

**Comment by chiragandroid** [comment]
ionicToast.show($filter('translate')("Hi ionic"), 'middle', false, 5000);
This is the solution of this issue. you need to inspect $filter in controller

**Comment by rajeshwarpatlolla** [comment]
Thanks for the answer.
