### ISSUE TITLE
first show toast,it don't display.

### ISSUE THREAD

**Issue by justwezzz** [rajeshwarpatlolla/ionic-toast#7]
first show toast,it don't display,when i turn to other page or click any button,it show

**Comment by zirbem07** [comment]
this line in ionic-toast.js: 

```
    $document.find('body').append(toastTemplate);
```

attempts to append the toast to body, however if your current view does not have a <body> tag the toast will not show. For me appending the toast to 'ion-pane' worked well.

```
    $document.find('ion-pane').append(toastTemplate);
```

**Comment by b3na** [comment]
I was having this issue, you need to do a $digest for the toast to show on your current view, try something like this:

``` javascript
  $scope.showToast = function(message){
    ionicToast.show(message, 'top', false, 3000);
    if(!$scope.$$phase) {
      $scope.$apply();
    }
  }
```

**Comment by bebertz93** [comment]
Just wrap the `ionicToast` with `$timeout`.

E.g.

``` javascript
$scope.showToast = function(message) {
  $timeout(function() {
    ionicToast.show(message, 'top', false, 3000);
  });
};
```

Hope this helps.
