### ISSUE TITLE
toastError, toastSuccess and toastWarning?

### ISSUE THREAD

**Issue by nidhhoggr** [rajeshwarpatlolla/ionic-toast#8]
Can you add styling and classes for the warning success and error toasts?

For instance, a warning toast would have a yellow background while a success toast would have a green background etc.

**Comment by rajeshwarpatlolla** [comment]
This is actually a nice feature to have it in this component. I will implement this feature and release a new version soon.

**Comment by rajeshwarpatlolla** [comment]
Your [PR](https://github.com/rajeshwarpatlolla/ionic-toast/pull/9) has been merged, which will have the functionality you mentioned here.
